version: '2'

services:
  codypaste-service:
    build: .
    container_name: codypaste-service
    volumes:
      - ./service/logs:/usr/src/app/logs
      - ./service:/usr/src/app
    environment:
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      REDIS_ENDPOINT: redis
      TIMEWINDOW_IN_SECONDS: 30
      QUOTA_IN_TIMEWINDOW: 10
    command: ['sh', '-c', 'yarn start']
    ports:
      - 3000:3000
    links:
      - mongoDB

  mongoDB:
    image: mongo:latest
    container_name: mongo_database
    volumes:
      - /home/mongo:/data/db
    ports:
    - "27017:27017"

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
