version: '3'

services:
  codypaste-service:
    image: 140303875034.dkr.ecr.eu-west-1.amazonaws.com/codypaste-snippets-service:latest
    volumes:
      - ./service/logs:/usr/src/app/logs
      - ./service:/usr/src/app
    environment:
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      REDIS_ENDPOINT: redis
      TIMEWINDOW_IN_SECONDS: 30
      QUOTA_IN_TIMEWINDOW: 1000 # high number so tests pass
      PRISMA_ENDPOINT: http://prisma-service:4466/codypaste/development
    command: ['sh', '-c', 'yarn start-dev']
    ports:
      - 3000:3000

  prisma:
    image: prismagraphql/prisma:1.23
    container_name: prisma-service
    ports:
      - "4466:4466"
    environment:
      PRISMA_MANAGEMENT_API_SECRET: abc
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: postgres
            migrations: true
            database: codypaste

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
